name: Full Stack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'back'
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
      working-directory: ./back
    - run: npm run build --if-present
      working-directory: ./back
    - run: npm test
      working-directory: ./back

  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'front'
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
      working-directory: ./front
    - run: npm run build --if-present
      working-directory: ./front
    - run: npm test
      working-directory: ./front