name: Full Stack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      working-directory: ./front  # Specify the correct directory here

    - name: Run the tests
      run: npm test
      working-directory: ./front  # Specify the correct directory here

    - name: Build
      run: npm run build
      working-directory: ./front  # Specify the correct directory here